### ISSUE TITLE
ref

### ISSUE THREAD

**Issue by kedixa** [ShomyLiu/myconfig#2]
- ShomyLiu/pytorch-relation-extraction#60

ShomyLiu/pytorch-relation-extraction#60

```
ShomyLiu/pytorch-relation-extraction#60
```

**Comment by kedixa** [comment]
click the ... then Edit, to see what is the different

**Comment by ShomyLiu** [comment]
@kedixa 
- kedixa/personal#1

kedixa/personal#1

**Comment by kedixa** [comment]
name changed
